// This file is auto-generated by Supabase CLI
// Run 'npm run generate:types' to regenerate types from your Supabase project
//
// To generate types:
// 1. Login to Supabase CLI: npx supabase login
// 2. Link your project: npx supabase link --project-ref vgdycmpevjiyfjrbskxf
// 3. Generate types: npm run generate:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Inserts<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type Updates<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          email?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          email?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      twitter_tokens: {
        Row: {
          id: string
          user_id: string
          access_token: string
          refresh_token: string | null
          expires_at: string | null
          twitter_user_id: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          access_token: string
          refresh_token?: string | null
          expires_at?: string | null
          twitter_user_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          access_token?: string
          refresh_token?: string | null
          expires_at?: string | null
          twitter_user_id?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      twitter_accounts: {
        Row: {
          user_id: string
          access_token: string
          refresh_token: string | null
          created_at: string | null
        }
        Insert: {
          user_id: string
          access_token: string
          refresh_token?: string | null
          created_at?: string | null
        }
        Update: {
          user_id?: string
          access_token?: string
          refresh_token?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      scheduled_tweets: {
        Row: {
          id: string
          user_id: string
          text: string
          scheduled_at: string
          status: string | null
          posted_at: string | null
          error_message: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          text: string
          scheduled_at: string
          status?: string | null
          posted_at?: string | null
          error_message?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          text?: string
          scheduled_at?: string
          status?: string | null
          posted_at?: string | null
          error_message?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
